export enum ErrorType {
  NETWORK_ERROR = "NETWORK_ERROR",
  GEOLOCATION_ERROR = "GEOLOCATION_ERROR",
  API_ERROR = "API_ERROR",
  PERMISSION_ERROR = "PERMISSION_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
